create table if not exists public.learning_examples (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  symbol text not null,
  interval_key text not null,
  feature_version text not null default 'v1',
  features jsonb not null,
  target integer not null check (target in (0,1)),
  future_return double precision,
  label_time timestamptz,
  source text not null default 'paper',
  event_key text unique
);

create index if not exists learning_examples_symbol_interval_idx
  on public.learning_examples (symbol, interval_key, created_at);
create index if not exists learning_examples_feature_version_idx
  on public.learning_examples (feature_version);
alter table public.learning_examples enable row level security;
revoke all on table public.learning_examples from anon, authenticated;

create table if not exists public.training_runs (
  id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running'
    check (status in ('running','completed','failed','rejected')),
  sample_count integer not null default 0 check (sample_count >= 0),
  metrics jsonb not null default '{}'::jsonb,
  error_message text
);
create index if not exists training_runs_started_idx
  on public.training_runs (started_at desc);
alter table public.training_runs enable row level security;
revoke all on table public.training_runs from anon, authenticated;

create table if not exists public.model_versions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  training_run_id uuid references public.training_runs(id) on delete set null,
  algorithm text not null,
  feature_version text not null,
  sample_count integer not null default 0 check (sample_count >= 0),
  validation_metrics jsonb not null default '{}'::jsonb,
  model_artifact_base64 text,
  promoted boolean not null default false,
  rejection_reason text
);
create index if not exists model_versions_created_idx
  on public.model_versions (created_at desc);
create index if not exists model_versions_promoted_idx
  on public.model_versions (promoted, created_at desc);
alter table public.model_versions enable row level security;
revoke all on table public.model_versions from anon, authenticated;
create unique index if not exists one_promoted_model_idx
  on public.model_versions (promoted) where promoted = true;

create table if not exists public.learning_state (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.learning_state enable row level security;
revoke all on table public.learning_state from anon, authenticated;
insert into public.learning_state (key, value)
values ('global', jsonb_build_object(
  'active_model_id', null,
  'feature_version', 'v1',
  'examples_seen', 0,
  'last_training_at', null
))
on conflict (key) do nothing;
